import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import { nunito } from "@/styles/fonts";
import { SideMenu } from "@/components/sideMenu";
import { Providers } from "@/app/providers";
import { Way } from "@/components/way";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          nunito.className
        )}
      >
        <Providers>
          <Header />
          <SideMenu />
          {children}
        </Providers>
      </body>
    </html>
  );
}
